dist: trusty

language: python
python:
  - "3.6"

env:
  global:
    - "MAIN_DB_HOST=localhost"

services:
  - mysql

before_install:
  - mysql -u root --password="" < db/init.sql

install:
  - pip install -r requirements.txt

before_script:
  - cd src/app
  - flask db upgrade
  - cd ../..
  - python ./src/app/db_seed.py

script:
  - python -m unittest discover
