version: "2"
services:
  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    volumes: 
      ['.:/dir']

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
